jhipster:
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: OTkzMTIyMTc5NTMxYzk4MGNhYzMzMzFlYjMwZGYxMTViZWFhZTExMTE5MzAyMDBjYmEzMTFlYTllY2MwNTQ4MjBkYTI5OGQ1NWUwYjNlODliYzk0MDY1YTFiZDJjM2ZhNzM3MmJlNzMwMzY1ODNkYmFhNzY4MmUwNDM3YjZlNzY=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
        
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 100 # Number of objects in each cache entry
  
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: true
      host: localhost
      port: 5000
      queue-size: 512
      
  registry:
    password: admin
        

