jhipster:
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: OTkzMTIyMTc5NTMxYzk4MGNhYzMzMzFlYjMwZGYxMTViZWFhZTExMTE5MzAyMDBjYmEzMTFlYTllY2MwNTQ4MjBkYTI5OGQ1NWUwYjNlODliYzk0MDY1YTFiZDJjM2ZhNzM3MmJlNzMwMzY1ODNkYmFhNzY4MmUwNDM3YjZlNzY=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
        
  registry:
    password: admin
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@ZAVSDCW10H8035:8761/eureka/
spring:      
  sleuth:
    # https://github.com/spring-projects/spring-framework/issues/27844#issuescomment-1002866885
    # https://github.com/spring-cloud/spring-cloud-sleuth/issues/2094
    async:
      enabled: false
    enabled: true
    sampler:
      probability: 1 # report 100% of traces
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://ZAVSDCW10H8035:9411
    enabled: true
    locator:
      discovery:
        enabled: true
